### ISSUE TITLE
Failure to compile on CentOS8

### ISSUE THREAD

**Issue by AlanCopeland-NTM** [hsoft/avra#6]
I have all GCC dependencies installed and have tried compiling other software with no issues.

output of make: 
[me@host:avra]$ make
make -C src -f makefiles/Makefile.linux
make[1]: Entering directory '/home/acopeland/avra/src'
gcc -static -o avra avra.o device.o parser.o expr.o mnemonic.o directiv.o macro.o file.o map.o coff.o args.o stdextra.o -s
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[1]: *** [makefiles/Makefile.linux:22: avra] Error 1
make[1]: Leaving directory '/home/acopeland/avra/src'
make: *** [Makefile:23: all] Error 2

**Comment by jbit** [comment]
It sounds like you need the `glibc-static` package. 

https://centos.pkgs.org/8/centos-powertools-x86_64/glibc-static-2.28-42.el8.1.x86_64.rpm.html
> glibc-static - C library static libraries for -static linking
